/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, clang++ 21.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "fsm.v:1.1-29.10" *)
module fsm(clk, reset, timer_done, r, g, y);
  (* src = "fsm.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "fsm.v:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "fsm.v:4.11-4.21" *)
  input timer_done;
  wire timer_done;
  (* src = "fsm.v:5.12-5.13" *)
  output r;
  wire r;
  (* src = "fsm.v:6.12-6.13" *)
  output g;
  wire g;
  (* src = "fsm.v:7.12-7.13" *)
  output y;
  wire y;
  wire _00_;
  wire _01_;
  wire _02_;
  (* src = "fsm.v:14.10-14.13" *)
  wire d_0;
  (* src = "fsm.v:15.10-15.13" *)
  wire d_1;
  (* src = "fsm.v:10.10-10.13" *)
  wire i_0;
  (* src = "fsm.v:11.10-11.13" *)
  wire s_0;
  (* src = "fsm.v:12.10-12.13" *)
  wire s_1;
  (* src = "fsm.v:9.15-9.20" *)
  reg [1:0] state;
  assign _01_ = state[0] & ~(state[1]);
  assign _02_ = ~(state[1] | state[0]);
  assign r = timer_done ? _01_ : _02_;
  assign _00_ = state[1] & ~(state[0]);
  assign d_0 = timer_done ? _00_ : _01_;
  assign d_1 = timer_done ? _02_ : _00_;
  (* src = "fsm.v:21.5-28.8" *)
  always @(posedge clk, posedge reset)
    if (reset) state[0] <= 1'h0;
    else state[0] <= d_0;
  (* src = "fsm.v:21.5-28.8" *)
  always @(posedge clk, posedge reset)
    if (reset) state[1] <= 1'h0;
    else state[1] <= d_1;
  assign s_1 = state[1];
  assign s_0 = state[0];
  assign i_0 = timer_done;
  assign y = d_0;
  assign g = d_1;
endmodule
