/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, clang++ 21.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "fsm.v:1.1-25.10" *)
module fsm(clk, reset, coin, dispense);
  (* src = "fsm.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "fsm.v:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "fsm.v:4.11-4.15" *)
  input coin;
  wire coin;
  (* src = "fsm.v:5.12-5.20" *)
  output dispense;
  wire dispense;
  wire _0_;
  wire _1_;
  (* src = "fsm.v:12.10-12.13" *)
  wire d_0;
  (* src = "fsm.v:13.10-13.13" *)
  wire d_1;
  (* src = "fsm.v:8.10-8.13" *)
  wire i_0;
  (* src = "fsm.v:9.10-9.13" *)
  wire s_0;
  (* src = "fsm.v:10.10-10.13" *)
  wire s_1;
  (* src = "fsm.v:7.15-7.20" *)
  reg [1:0] state;
  assign _0_ = ~state[1];
  assign _1_ = state[1] & ~(state[0]);
  assign d_0 = coin & _1_;
  assign d_1 = coin ? _0_ : _1_;
  (* src = "fsm.v:17.5-24.8" *)
  always @(posedge clk, posedge reset)
    if (reset) state[0] <= 1'h0;
    else state[0] <= d_0;
  (* src = "fsm.v:17.5-24.8" *)
  always @(posedge clk, posedge reset)
    if (reset) state[1] <= 1'h0;
    else state[1] <= d_1;
  assign s_1 = state[1];
  assign s_0 = state[0];
  assign i_0 = coin;
  assign dispense = d_0;
endmodule
