/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, clang++ 21.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "fsm.v:1.1-22.10" *)
module fsm(clk, reset, x, is_even);
  (* src = "fsm.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "fsm.v:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "fsm.v:4.11-4.12" *)
  input x;
  wire x;
  (* src = "fsm.v:5.12-5.19" *)
  output is_even;
  wire is_even;
  (* src = "fsm.v:11.10-11.13" *)
  wire d_0;
  (* src = "fsm.v:8.10-8.13" *)
  wire i_0;
  (* src = "fsm.v:9.10-9.13" *)
  wire s_0;
  (* src = "fsm.v:7.9-7.14" *)
  reg state;
  assign is_even = ~(x ^ state);
  assign d_0 = x ^ state;
  (* src = "fsm.v:15.5-21.8" *)
  always @(posedge clk, posedge reset)
    if (reset) state <= 1'h0;
    else state <= d_0;
  assign s_0 = state;
  assign i_0 = x;
endmodule
