/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, clang++ 21.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "fsm.v:1.1-29.10" *)
module fsm(clk, reset, in1, in0, o1, o0);
  (* src = "fsm.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "fsm.v:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "fsm.v:4.11-4.14" *)
  input in1;
  wire in1;
  (* src = "fsm.v:5.11-5.14" *)
  input in0;
  wire in0;
  (* src = "fsm.v:6.12-6.14" *)
  output o1;
  wire o1;
  (* src = "fsm.v:7.12-7.14" *)
  output o0;
  wire o0;
  (* src = "fsm.v:15.10-15.13" *)
  wire d_0;
  (* src = "fsm.v:16.10-16.13" *)
  wire d_1;
  (* src = "fsm.v:10.10-10.13" *)
  wire i_0;
  (* src = "fsm.v:11.10-11.13" *)
  wire i_1;
  assign d_0 = in1;
  assign i_1 = in0;
  assign i_0 = in1;
  assign d_1 = in0;
  assign o0 = in0;
  assign o1 = in1;
endmodule
