/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, clang++ 21.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "fsm.v:1.1-29.10" *)
module fsm(clk, reset, reqA, reqB, ackA, ackB);
  (* src = "fsm.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "fsm.v:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "fsm.v:4.11-4.15" *)
  input reqA;
  wire reqA;
  (* src = "fsm.v:5.11-5.15" *)
  input reqB;
  wire reqB;
  (* src = "fsm.v:6.12-6.16" *)
  output ackA;
  wire ackA;
  (* src = "fsm.v:7.12-7.16" *)
  output ackB;
  wire ackB;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "fsm.v:15.10-15.13" *)
  wire d_0;
  (* src = "fsm.v:16.10-16.13" *)
  wire d_1;
  (* src = "fsm.v:10.10-10.13" *)
  wire i_0;
  (* src = "fsm.v:11.10-11.13" *)
  wire i_1;
  (* src = "fsm.v:12.10-12.13" *)
  wire s_0;
  (* src = "fsm.v:13.10-13.13" *)
  wire s_1;
  (* src = "fsm.v:9.15-9.20" *)
  reg [1:0] state;
  assign _02_ = state[0] | ~(reqA);
  assign _03_ = ~(state[1] & state[0]);
  assign _04_ = reqB & _03_;
  assign ackB = _02_ & _04_;
  assign _00_ = ~(reqB | state[1]);
  assign _01_ = ~(reqA & _00_);
  assign d_1 = ~(_02_ & _01_);
  (* src = "fsm.v:21.5-28.8" *)
  always @(posedge clk, posedge reset)
    if (reset) state[0] <= 1'h0;
    else state[0] <= ackB;
  (* src = "fsm.v:21.5-28.8" *)
  always @(posedge clk, posedge reset)
    if (reset) state[1] <= 1'h0;
    else state[1] <= d_1;
  assign d_0 = ackB;
  assign s_1 = state[1];
  assign s_0 = state[0];
  assign i_1 = reqB;
  assign i_0 = reqA;
  assign ackA = d_1;
endmodule
