/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, clang++ 21.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "fsm.v:1.1-27.10" *)
module fsm(clk, reset, en, q1, q0);
  (* src = "fsm.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "fsm.v:3.11-3.16" *)
  input reset;
  wire reset;
  (* src = "fsm.v:4.11-4.13" *)
  input en;
  wire en;
  (* src = "fsm.v:5.12-5.14" *)
  output q1;
  wire q1;
  (* src = "fsm.v:6.12-6.14" *)
  output q0;
  wire q0;
  wire _0_;
  (* src = "fsm.v:13.10-13.13" *)
  wire d_0;
  (* src = "fsm.v:14.10-14.13" *)
  wire d_1;
  (* src = "fsm.v:9.10-9.13" *)
  wire i_0;
  (* src = "fsm.v:10.10-10.13" *)
  wire s_0;
  (* src = "fsm.v:11.10-11.13" *)
  wire s_1;
  (* src = "fsm.v:8.15-8.20" *)
  reg [1:0] state;
  assign _0_ = ~(state[1] & en);
  assign d_0 = ~(state[0] ^ _0_);
  assign q0 = state[1] ^ en;
  (* src = "fsm.v:19.5-26.8" *)
  always @(posedge clk, posedge reset)
    if (reset) state[0] <= 1'h0;
    else state[0] <= d_0;
  (* src = "fsm.v:19.5-26.8" *)
  always @(posedge clk, posedge reset)
    if (reset) state[1] <= 1'h0;
    else state[1] <= q0;
  assign d_1 = q0;
  assign s_1 = state[1];
  assign s_0 = state[0];
  assign i_0 = en;
  assign q1 = d_0;
endmodule
